name: Run Node file
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node -v
      - run: npm -v
      - uses: actions/checkout@v3
      - run: node index.js